EOS-23641: Add CRC support for btree.
Seagate/cortx-motr pull request #1032
Opened 2021-09-07 12:16 UTC by NikhilBirgade

Signed-off-by: Nikhil Kumar Birgade <nikhil.birgade@seagate.com>

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *	c. CRC is updated when a record us added or deleted.
s/us/is

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *	d. While traversing down the tree for the first time  for any operation
extra space after time

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *	e. For get and delete operation if tree traversal reaches leaf node and
comma after operation

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *	do not find the record then tree traversal will be re-initiated with CRC
s/do/does

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *		ii.Only the checksum of the newly added key is calculated and
space after ii.

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *		ii.We worry about this issue if we have a way to fix the tree
space after ii.

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *	b. Mote will calculate individual checksum for each key and save it next
s/Mote/Motr

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *		ii.Only the checksum of the newly added key is calculated and
space after ii.

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *		i.Checksum of all the keys are verified when node is loaded from
space after i.

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *		i.Checksum of all the keys are verified when node is loaded from
space after i.

2021-09-08 10:32 UTC, ydb242 commented on btree/btree.c
> + *	a. For internal nodes, Motr will calculate CRCs of only Keys.
s/Keys/keys

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *	a. For internal nodes, Motr will calculate CRCs of only Keys.
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *	c. CRC is updated when a record us added or deleted.
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *	d. While traversing down the tree for the first time  for any operation
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *	e. For get and delete operation if tree traversal reaches leaf node and
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *	do not find the record then tree traversal will be re-initiated with CRC
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *		ii.We worry about this issue if we have a way to fix the tree
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *		i.Checksum of all the keys are verified when node is loaded from
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *		ii.Only the checksum of the newly added key is calculated and
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *	b. Mote will calculate individual checksum for each key and save it next
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *		i.Checksum of all the keys are verified when node is loaded from
Done.

2021-09-08 11:36 UTC, NikhilBirgade commented on btree/btree.c
> + *		ii.Only the checksum of the newly added key is calculated and
Done.

2021-09-09 05:03 UTC, ydb242 approved these changes

2021-09-13 06:10 UTC, RadhaGulhane13 approved these changes

2021-09-16 13:55 UTC, shashank-parulekar requested changes

2021-09-17 04:57 UTC, NikhilBirgade commented on btree/btree.c
> + *	some sanity checks will be used to verify the values.
Done.

2021-09-17 04:57 UTC, NikhilBirgade commented on btree/btree.c
> + *		whatever location we have found and continue. This is because
Done.

2021-09-17 04:57 UTC, NikhilBirgade commented on btree/btree.c
> + *		the path is corrupted anyways and there is no way to recover the
Done.

2021-09-17 04:57 UTC, NikhilBirgade commented on btree/btree.c
> + *		bad path and reach the correct location.
Done.

2021-09-17 04:57 UTC, NikhilBirgade commented on btree/btree.c
> + *		fixed.
Done.

2021-09-17 04:57 UTC, NikhilBirgade commented on btree/btree.c
> + * These are the proposal for supporting CRCs in the node:
Done.

2021-09-17 04:57 UTC, NikhilBirgade commented on btree/btree.c
> + *		traversed for calculating CRC of the keys.
Done.

2021-09-17 17:56 UTC, shashank-parulekar approved these changes

2021-09-17 17:56 UTC, shashank-parulekar commented on btree/btree.c
> + *		redundant tree and continue. This way the btree is corrupted
s/corrupted/corrected/

2021-09-20 04:54 UTC, NikhilBirgade commented on btree/btree.c
> + *		redundant tree and continue. This way the btree is corrupted
Done.

2021-09-20 04:55 UTC, merged