Changes in btree.c for integration purpose
Seagate/cortx-motr pull request #1076
Opened 2021-09-24 10:07 UTC by RadhaGulhane13

Signed-off-by: Radha Gulhane <radha.gulhane@seagate.com>

2021-09-24 11:04 UTC, NikhilBirgade approved these changes

2021-09-24 11:47 UTC, NikhilBirgade approved these changes

2021-09-24 14:03 UTC, shashank-parulekar requested changes

2021-09-24 14:03 UTC, shashank-parulekar commented on btree/btree.c
> +		if (rc == 0)
This should be (rc != 0)

2021-09-24 14:03 UTC, shashank-parulekar commented on btree/btree.c
> +		if (rc)
since rc is of type 'int' the check should be if (rc != 0)

2021-09-27 05:16 UTC, RadhaGulhane13 commented on btree/btree.c
> +		if (rc == 0)
done.

2021-09-27 05:53 UTC, ydb242 approved these changes

2021-10-05 03:21 UTC, shashank-parulekar approved these changes

2021-10-05 03:22 UTC, merged