EOS-23901: CRC design for variable sized key and value node format
Seagate/cortx-motr pull request #1353
Opened 2021-12-30 09:30 UTC by RadhaGulhane13

Signed-off-by: Radha Gulhane <radha.gulhane@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2021-12-30 09:40 UTC, shashank-parulekar requested changes

2021-12-30 09:40 UTC, shashank-parulekar commented on btree/btree.c
> + * Value.
```suggestion
 * CRC will be calculated and updated in the record by BTree module when a record is inserted or updated
 * This CRC will be placed at the end of Value. Verification
 * of CRC will be done whenever the node descriptor is loaded from the storage.
```

2021-12-30 09:40 UTC, shashank-parulekar commented on btree/btree.c
> + * of CRC will be done whenever the node descriptor will be loaded.
```suggestion
 * of CRC will be done whenever the node descriptor is loaded from the storage.
```

2021-12-30 10:11 UTC, ydb242 approved these changes

2021-12-31 03:41 UTC, shashank-parulekar approved these changes

2021-12-31 04:27 UTC, merged