EOS-14409 be/tool/beck: provide option to resume scan
Seagate/cortx-motr pull request #141
Opened 2020-10-21 06:48 UTC by mukundkanekar

Problem:
Beck tool crashes when run into out of memory.  Motr recovery script relaunches beck which starts scan from offset 0 again. This can cause recovery run to take longer time.

Solution:
Save offset of  metadata record currently being processed by builder. This offset indicates previous metadata records are processed and are in persistent state. Beck tool relaunch can start from saved offset.
1. beck tool is updated to,
  a.  take command line argument's for file name to save scan offset and enable scan resume from saved offset.
  b.  save current metadata record offset periodically.
2. motr recovery script change to,
  a. provide file name to save scan offset.
  b. enable scan resume on beck tool relaunch.
  c. relaunch beck tool on Out Of Memory exit code in addition to previous SEG fault.

2020-10-22 06:13 UTC, kanchan-chaudhari approved these changes
Approved changes for scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh file.

2020-10-28 06:08 UTC, RakeshVaghasiya commented
Need to update as per latest builder and scanner implementation against jira ticket EOS-14234

2020-10-28 06:10 UTC, RakeshVaghasiya requested changes
Need to update as per latest proposed changes for scanner and builder implementation against EOS-14234

2020-11-10 09:15 UTC, huanghua78 commented on scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
> +             -g $REMOTE_SEG_GEN_ID -r $MD_DIR/scan_offset;)
Can we save this in a variable and then use it in both places?

This will avoid duplicate the same string in two places.

2020-11-10 09:17 UTC, huanghua78 commented on scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
> +                 -g $REMOTE_SEG_GEN_ID -r $MD_DIR/scan_offset -R;)
And if we save the command string in a variable, we can use it here too.

2020-11-10 09:17 UTC, huanghua78 commented
What is the status of this PR, @mukundkanekar ?

2020-11-11 08:44 UTC, mukundkanekar commented
> What is the status of this PR, @mukundkanekar ?

Changes in this PR are no  longer valid with recent perf changes done via EOS-14234.
The changes in progress, will close this PR with link to new PR once created.

2020-11-24 16:14 UTC, mukundkanekar commented
New PR #234 is created to provide scan resume functionality on top of recent perf changes done via EOS-14234.

2020-11-24 16:14 UTC, closed without merging