CORTX-27957: Add st for DIX repair using m0repair utility.
Seagate/cortx-motr pull request #1494
Opened 2022-02-17 13:40 UTC by sanjognaik

# Problem Statement
- Currently DIX repair STs use m0spiel utility for repair and rebalance, whereas SNS repair STs are use m0spiel as well as m0repair utilities. So new STs are added for DIX repair to use m0repair utility.

# Design
- Added enpoint for DIX CLI and DIX QUIESCE CLI
- Added Motr DIX repair ST using m0repair
- Added m0t1fs DIX repair ST using m0repair

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-02-18 15:23 UTC, shashank-parulekar requested changes

2022-02-21 06:21 UTC, sanjognaik commented on dix/cm/st/m0t1fs_dix_repair_quiesce.sh
> +
Already done.

2022-02-21 07:11 UTC, sanjognaik commented on dix/cm/st/dix_repair_st.sh
>  	cas_disk_state_set "repaired" $fail_device
Done.

2022-02-21 07:11 UTC, sanjognaik commented on dix/cm/st/dix_repair_st.sh
>  	cas_disk_state_set "online" $fail_device
Done.

2022-02-21 07:11 UTC, sanjognaik commented on dix/cm/st/m0t1fs_dix_repair.sh
> +	if [[ $rc -eq 0 ]] && ! dix_repair_test ; then
Done.

2022-02-21 10:16 UTC, nkommuri approved these changes

2022-02-21 10:21 UTC, shashank-parulekar approved these changes

2022-02-21 10:54 UTC, merged