CORTX-28510: Include PID into ADDB domain name in m0add2dump utility
Seagate/cortx-motr pull request #1528
Opened 2022-03-09 09:27 UTC by rahul27kumar

ADDB domain name is changed to include PID as a postfix
Ex:
   "_addb2-dump" to "addb2-dump_<PID>"

Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>

2022-03-17 06:22 UTC, maximalezhin requested changes
Please address CR notes.

2022-03-17 06:22 UTC, maximalezhin commented on addb2/dump.c
> +#include "lib/thread.h"
Please specify function that is used in comments:
Example: 
`#include "lib/thread.h"       /* m0_pid() */  `

2022-03-17 06:22 UTC, maximalezhin commented on addb2/dump.c
> +	char                    buff[80];
Spelling: buffer name `buf` is more commonly used.

2022-03-23 04:53 UTC, yeshpal-jain-seagate approved these changes

2022-03-23 05:33 UTC, merged