EOS-27770: Motr mini provisioner log rotate
Seagate/cortx-motr pull request #1529
Opened 2022-03-10 03:29 UTC by atulsdeshmukh2312

Signed-off-by: Atul Deshmukh <atul.deshmukh@seagate.com>

# Problem Statement
Restrict max size and max copies of motr mini provisioner log file with log rotation. 

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-03-21 13:45 UTC, yeshpal-jain-seagate requested changes
We can move log rotate start and other function from background to crond job.

2022-03-21 13:45 UTC, yeshpal-jain-seagate commented on scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
> +    size 100M
why do we want to keep 100M uncompressed log file, any idea how long a 100M file will provide us the data, instead decrease uncompressed size and increase number of compressed file

2022-03-21 13:45 UTC, yeshpal-jain-seagate commented on scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
> +def add_entry_to_logrotate_conf_file(self):
fix the codacy issues

2022-03-21 13:45 UTC, yeshpal-jain-seagate commented on scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
> +           "{a}\n".format(a='}')]
what will the compression format, we want to use

2022-03-21 13:45 UTC, yeshpal-jain-seagate commented on scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
> +    with open(f"{LOGROTATE_MOTR_CONF_FILE}", 'w+') as fp:
fix codacy issue here and wherever is there

2022-03-21 13:45 UTC, yeshpal-jain-seagate commented on scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
> +    execute_command_verbose(self, cmd, set_timeout=False)
Add some timeout, if it fails then fail with error.

2022-03-22 14:31 UTC, yeshpal-jain-seagate commented on scripts/install/opt/seagate/cortx/motr/libexec/motr_mini_prov_logrotate.sh
> +/usr/sbin/logrotate /etc/cortx/motr/mini_prov_logrotate.conf
check if file is available

2022-03-22 14:33 UTC, yeshpal-jain-seagate commented on scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
> +    size 10M
are we collecting all the files in support bundle

2022-04-05 11:05 UTC, atulsdeshmukh2312 commented
New PR: https://github.com/Seagate/cortx-motr/pull/1589

2022-04-05 11:05 UTC, closed without merging