Update CORTX-MOTR-ARCHITECTURE.md
Seagate/cortx-motr pull request #1563
Opened 2022-03-24 18:18 UTC by johnbent

Adding link to parity declustered design document. Why is it in a documentation branch though instead of in main?

Signed-off-by: John Bent <john.bent@seagate.com>

2022-03-25 15:21 UTC, nikitadanilov requested changes

2022-03-25 15:21 UTC, nikitadanilov commented on doc/CORTX-MOTR-ARCHITECTURE.md
> +   + More details about [parity declustering](https://github.com/Seagate/cortx-motr/blob/documentation/doc/pdclust/index.rst)
Agree, let's move this to main and them re-issue this PR.

2022-03-25 15:23 UTC, nikitadanilov commented on doc/CORTX-MOTR-ARCHITECTURE.md
> +   + More details about [parity declustering](https://github.com/Seagate/cortx-motr/blob/documentation/doc/pdclust/index.rst)
https://github.com/Seagate/cortx-motr/blob/documentation/doc/sm/index.rst can also be moved to main: it's another deep dive document.

2022-04-18 04:25 UTC, nikitadanilov approved these changes

2022-07-28 05:32 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-08-22 09:21 UTC, andriytk approved these changes

2022-08-22 09:23 UTC, andriytk commented
@mehjoshi, it can be landed now, i think.

2022-08-22 10:22 UTC, mehjoshi commented
> @mehjoshi, it can be landed now, i think.

Sure.
@rkothiya, Could you please merge this PR once the deployment and other checks complete? Thanks.

2022-08-29 09:53 UTC, rkothiya commented
giving an exception for pre-merge and ci/cd regression job as this is related to documentation.

2022-08-29 09:55 UTC, merged