lib/alloc_prof.[ch]: add simple memory allocator profiler.
Seagate/cortx-motr pull request #1626
Opened 2022-04-13 22:14 UTC by nikitadanilov

See lib/alloc_prof.h for the documentation.

Signed-off-by: Nikita Danilov <nikita.danilov@seagate.com>

2022-04-14 05:11 UTC, nikitadanilov commented
As an example, the allocator profile output for the full UT run (usesock branch):
```
$ sort -k3 -n ~/tmp/usesock-ut-alloc-prof | tail
     alloc      19833  403433688   120 cas/service.c 671 cas_fom_create repv
     alloc       7047  451008000   859 net/sock/sock.c 4696 get_fd fd->md_buf.u_sock
     alloc      32969  815257432    61 ha/msg_queue.c 58 m0_ha_msg_queue_alloc qitem
     alloc     256795  922017611  5382 lib/memory.c 128 m0_alloc m0_alloc
     alloc      20649 2079782152    35 be/io.c 192 m0_be_io_allocate bv->ov_vec.v_count
     alloc      20649 2079782152    35 be/io.c 193 m0_be_io_allocate bv->ov_buf
     alloc      20649 2079782152    35 be/io.c 194 m0_be_io_allocate iv->iv_vec.v_count
     alloc      20649 2079782152    35 be/io.c 195 m0_be_io_allocate iv->iv_index
     alloc       5287 4160343280     3 be/fmt.c 259 m0_be_fmt_group_init cheader->fch_reg_area.chr_reg
     alloc       5287 4160343280     3 be/fmt.c 267 m0_be_fmt_group_init content->fmc_reg_area.cra_reg

2022-04-14 09:40 UTC, andriytk commented
@nikitadanilov, https://cbea.ms/git-commit/#end

2022-04-14 09:51 UTC, andriytk commented
> As an example, the allocator profile output for the full UT run (usesock branch):

@nikitadanilov, it would be useful to add a few comments on the result of this profiling - what the numbers mean, how to interpret them, etc.

2022-04-14 09:52 UTC, andriytk approved these changes

2022-04-14 12:23 UTC, shashank-parulekar requested changes

2022-04-14 12:23 UTC, shashank-parulekar commented on lib/alloc_prof.c
> +static struct m0_alloc_prof_tls ptdata[AP_NR][SLOTS] = {};
This variable is supposed to be per thread according to the documentation for struct m0_alloc_prof_tls.

2022-04-14 12:23 UTC, shashank-parulekar commented on lib/memory.h
> +void *m0_alloc_profiled(size_t size, struct m0_alloc_prof *ap);
Compile error is seen for this line on current code base.

2022-04-14 13:52 UTC, nikitadanilov commented on lib/alloc_prof.c
> +	struct m0_alloc_prof_tls *pt = &ptdata[atype][ap - begin];
It seems you are looking at the alloc-profile branch and not at the PR. I made some further experimental undebugged changes to the branch. Please review the commits in the PR only.

2022-04-25 07:35 UTC, huanghua78 approved these changes

2022-04-29 05:49 UTC, closed without merging