CORTX-30993 - BE: Avoid usage of gft_tmp_op to put group fom op into active state
Seagate/cortx-motr pull request #1820
Opened 2022-05-26 09:49 UTC by vidyadhar-pinglikar

RCA:  Due to recursive calls to be_op_state_change where gc callback of gft_op i.e. child1 invokes done callback of gft_tmp_op i.e. child 2 which subsequently results in invocation of parent be_op_state_change. This results in group fom getting completed ahead of child op callback processing. so the subsequently crash is observed when group is reused before child callback processing is finished. 
Fix: Avoid usage of gft_tmp_op and set the main parent op into active set before adding gft_op as a child to itself.

Signed-off-by: Vidyadhar Pinglikar <vidyadhar.pinglikar@seagate.com>

# Problem Statement
- Crashes at multiple places seen in m0_be_op_fini(&gft->gft_tmp_op) and m0_be_op_fini(op) during be_tx_group_format_seg_io_op_gc callback processing.

# Design
-  RCA:  Due to recursive calls to be_op_state_change where gc callback of gft_op i.e. child1 invokes done callback of gft_tmp_op i.e. child 2 which subsequently results in invocation of parent be_op_state_change. This results in group fom getting completed ahead of child op callback processing. so the subsequently crash is observed when group is reused before child callback processing is finished. 
Fix: Avoid usage of gft_tmp_op and set the main parent op into active set before adding gft_op as a child to itself.

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-05-27 11:23 UTC, chandradharraval commented
Hi @max-seagate ,
Can you review this PR on priority, as we would like to merge this fix for IOstability goal

2022-06-02 13:59 UTC, max-seagate requested changes
The description doesn't allow to understand what the bug is. The ticket on jira doesn't help either.

> so the subsequently crash is observed when group is reused before child callback processing is finished

Would you please post backtraces and/or logs to show this? It's not clear what kind of "group reuse" leads to the crash and what the sequence of events is. As I understand the description of the bug in the PR description stops just before the crash is observed, and it only covers one thread. Please add a sequence of events in all relevant threads and the reason why the crash happens.

> Crashes at multiple places seen in m0_be_op_fini(&gft->gft_tmp_op) and m0_be_op_fini(op) during be_tx_group_format_seg_io_op_gc callback processing.

It would be nice to have backtraces and/or traces for those crashes in this PR as well.

> Fix: Avoid usage of gft_tmp_op and set the main parent op into active set before adding gft_op as a child to itself.

Please describe why this would prevent the crash from happening.

2022-06-03 09:54 UTC, vidyadhar-pinglikar commented
https://jts.seagate.com/secure/attachment/519610/30993_core_107_scratch.txt

Currently this scratch file is attached in jira which describes the basic crash reason  based on the core file data and respective snippet of crash; we dont have m0trace for corresponding timeline to provide the back trace; 
Though, will update the above file with more details regarding the RCA and how fix helps to avoid the problem

2022-06-03 13:28 UTC, max-seagate commented
The scratch file above contains a cut version of a single backtrace and no m0traces.

> we dont have m0trace for corresponding timeline to provide the back trace;

By "backtrace" I mean https://sourceware.org/gdb/onlinedocs/gdb/Backtrace.html, by "traces" or  "m0traces" I mean output from `m0trace` tool.

2022-06-06 10:19 UTC, vidyadhar-pinglikar commented
Added https://jts.seagate.com/secure/attachment/520888/30993_core_107_RCA_FIX_scratch_0606.txt 
with more details.

2022-06-06 16:34 UTC, max-seagate commented
The root cause analysis looks good and the fix seems to be correct.

The only work left here is to add the following to the PR description:
- panic messages for this bug;
- stack backtraces seen on panic;
- root cause analysis (sequence of events, info from gdb etc.) and explanation of the fix, like in the documents from Jira above.

2022-06-07 04:57 UTC, vidyadhar-pinglikar commented
Updated the PR description with required details.

2022-06-07 10:28 UTC, mehjoshi commented
started the following test job for testing this PR:
https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/1313/

2022-06-07 17:05 UTC, mehjoshi commented
> The root cause analysis looks good and the fix seems to be correct.
> 
> The only work left here is to add the following to the PR description:
> 
> * panic messages for this bug;
> * stack backtraces seen on panic;
> * root cause analysis (sequence of events, info from gdb etc.) and explanation of the fix, like in the documents from Jira above.

Based on the following comment from Max and the following changes to the PR description from @vidyadhar-pinglikar incorporating the changes suggested by Max here, I suppose we are good to merge this change. I will thus go ahead and merge it. @max-seagate, please let me know in case you disagree and would like it to be reverted.

2022-06-07 17:08 UTC, merged

2022-06-07 21:19 UTC, max-seagate commented
@mehjoshi: you're right to merge it.