CORTX-30955 : Fix Codacy issues for be/fmt.c be/ha.c
Seagate/cortx-motr pull request #1829
Opened 2022-05-26 14:25 UTC by papan-singh

Signed-off-by: Papan Kumar Singh <papan.kumarsingh@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-05-30 13:13 UTC, papan-singh commented on be/fmt.c
> -	fctx.cfg = cfg;
> Please explain this change. be_fmt_alloc() actually accesses fctx.cfg.

fctx is local variable inside function be_fmt_decode()
Variable 'fctx.cfg' is assigned a value that is never used.

2022-05-30 16:10 UTC, nikitadanilov requested changes

2022-05-30 16:10 UTC, nikitadanilov commented on be/fmt.c
> -	fctx.cfg = cfg;
Pointer to fctx.ctx is stored in ctx. ctx is passed to m0_xcode_decode(). be_fmt_alloc() casts ctx to fctx and accesses fctx->cfg. "fctx" is a local variable in be_fmt_alloc() that points to fctx allocated on stack by be_fmt_decode():

```
static void *be_fmt_alloc(struct m0_xcode_cursor *it, size_t nob)
{
	struct m0_xcode_ctx *xctx =
		container_of(it, struct m0_xcode_ctx, xcx_it);
	struct m0_fmt_xcode_ctx *fctx =
		container_of(xctx, struct m0_fmt_xcode_ctx, ctx);
```

Is it codacy that thinks that "fctx.cfg" is not used?

2022-05-30 20:28 UTC, nikitadanilov requested changes

2022-05-30 20:28 UTC, nikitadanilov commented on be/ha.c
> -	M0_PRE(errcode < 0);
But how it worked before? An unsigned value cannot be less than 0, so this assertion is always false. Why hasn't it triggered?

2022-06-02 07:27 UTC, papan-singh commented on be/fmt.c
> -	fctx.cfg = cfg;
> Is it codacy that thinks that "fctx.cfg" is not used?
yes

2022-06-02 08:36 UTC, papan-singh commented on be/ha.c
> -	M0_PRE(errcode < 0);
> But how it worked before? An unsigned value cannot be less than 0, so this assertion is always false. Why hasn't it triggered?

this code never executed

2022-06-06 16:42 UTC, nikitadanilov commented
I still want to understand the source of "`fctx.cfg` is unused" statement. Was this reported by Codacy? If so, could you please show the exact Codacy report?

As for `errcode < 0` assertion: if you look at the callers of `m0_be_io_err_send()`, you would see that `errcode` is supposed to be a positive (i.e., not negated) `errno` value. The correct assertion should have been `M0_PRE(errcode > 0)`. Instead of just removing an obviously incorrect code, one should first try to understand why it is there.

2022-06-07 07:57 UTC, papan-singh commented
> I still want to understand the source of "`fctx.cfg` is unused" statement. Was this reported by Codacy? If so, could you please show the exact Codacy report?
> 
> As for `errcode < 0` assertion: if you look at the callers of `m0_be_io_err_send()`, you would see that `errcode` is supposed to be a positive (i.e., not negated) `errno` value. The correct assertion should have been `M0_PRE(errcode > 0)`. Instead of just removing an obviously incorrect code, one should first try to understand why it is there.

link to source of "`fctx.cfg` is unused" statement
https://app.codacy.com/gh/Seagate/cortx-motr/file/71857620524/issues/source?bid=28564742&fileBranchId=28564742#l145

2022-06-09 09:02 UTC, papan-singh commented on be/ha.c
> -	M0_PRE(errcode < 0);
incorporated

2022-06-09 15:49 UTC, nikitadanilov commented
> > I still want to understand the source of "`fctx.cfg` is unused" statement. Was this reported by Codacy? If so, could you please show the exact Codacy report?
> > As for `errcode < 0` assertion: if you look at the callers of `m0_be_io_err_send()`, you would see that `errcode` is supposed to be a positive (i.e., not negated) `errno` value. The correct assertion should have been `M0_PRE(errcode > 0)`. Instead of just removing an obviously incorrect code, one should first try to understand why it is there.
> 
> link to source of "`fctx.cfg` is unused" statement https://app.codacy.com/gh/Seagate/cortx-motr/file/71945097240/issues/source?bid=28564742&fileBranchId=28564742#l145

The link is broken.

2022-06-10 04:03 UTC, yatin-mahajan approved these changes
[suggestion]
May be you can add commit message as well if possible. 

Looks good to me,

2022-06-10 08:31 UTC, mehjoshi commented
I have started the following jenkins test job:
https://eos-jenkins.colo.seagate.com/job/Motr/job/Motr-Pr-Test-GF3VM/574/

2022-06-10 08:38 UTC, papan-singh commented
> > > I still want to understand the source of "`fctx.cfg` is unused" statement. Was this reported by Codacy? If so, could you please show the exact Codacy report?
> > > As for `errcode < 0` assertion: if you look at the callers of `m0_be_io_err_send()`, you would see that `errcode` is supposed to be a positive (i.e., not negated) `errno` value. The correct assertion should have been `M0_PRE(errcode > 0)`. Instead of just removing an obviously incorrect code, one should first try to understand why it is there.
> > 
> > 
> > link to source of "`fctx.cfg` is unused" statement https://app.codacy.com/gh/Seagate/cortx-motr/file/71945097240/issues/source?bid=28564742&fileBranchId=28564742#l145
> 
> The link is broken.

" right now there is some issue with Codacy servers and running Codacy tool on PRs is disabled temporarily since today morning. Once the issue with Codacy servers is fixed and if the same issue is seen again, I will add an update".

2022-06-10 13:03 UTC, mehjoshi commented
retest this please

2022-06-13 05:25 UTC, mehjoshi commented
> I have started the following jenkins test job: https://eos-jenkins.colo.seagate.com/job/Motr/job/Motr-Pr-Test-GF3VM/574/

I had restarted test for this PR. Following is the link to its report:
https://eos-jenkins.colo.seagate.com/job/Motr/job/Motr-Pr-Test-GF3VM/581/testReport/

2022-06-13 05:27 UTC, mehjoshi commented
There are 4 failures observed in the report from https://eos-jenkins.colo.seagate.com/job/Motr/job/Motr-Pr-Test-GF3VM/581/testReport. Two of the failures are known issues while the other two are seen while invoking confc related functionality. I don't think these failures are caused by or influenced by the current changes in the PR. Hence, I will merge this PR.

2022-06-13 05:29 UTC, merged