Adding an ADDB user guide
Seagate/cortx-motr pull request #2123
Opened 2022-09-02 18:24 UTC by faradawn

Signed-off-by: faradawn <faradawny@gmail.com>

# Problem Statement
- cortx-motr lacks a thorough documentation on ADDB

# Design
- Created a ADDB guide for users to build motr, perform an IO, and construct a ADDB graph.
- No coding is involved

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-09-02 18:26 UTC, rkothiya commented
Can one of the admins verify this patch?

2022-09-06 09:58 UTC, andriytk commented on doc/ADDB-User-Guide.md
> +- Or on a Skylake CENTOS 7.9 baremetal
Why is this needed? Is ADDB specific or depents on these platforms? Not sure. Please remove, if not.

2022-09-06 09:59 UTC, andriytk commented on doc/ADDB-User-Guide.md
> +git checkout 58f3d69e51a049eb5d5e2576040cc5ee732e2410
Why specific commit id? Won't it work on the latest main branch?

2022-09-06 10:01 UTC, andriytk commented on doc/ADDB-User-Guide.md
> +## Part 1 - Building Motr
Building motr is covered at https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst, why is this needed here? Are there some special steps needed for ADDB?

2022-09-06 10:15 UTC, andriytk requested changes
More than half of this document is about how to build and start Motr. But there are such documents already (see [QSG](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst), for example), there is no need to duplicate them.

It would be nice to have some introduction words about ADDB: what it is, why it is needed and how it can help. Providing some real-world usage examples and problem(s) analysis would be very beneficial for this document.

2022-09-07 15:28 UTC, faradawn commented
Hi Andriy,

Have carefully edited the ADDB_User_Guide according to your comments:
- added a description of what ADDB can be used for
- explained what this guide does: generate a request graph for bottleneck analysis
- removed the redundant motr installation steps 
- simplified the ADDB graph generating process

Thank you for taking a look at the guide. Your suggestions meant a lot!

Thanks,
Faradawn

2022-09-09 09:35 UTC, siningwuseagate commented on doc/ADDB-User-Guide.md
> +[ADDB](https://github.com/Seagate/cortx-motr/blob/main/doc/ADDB.md) can track how long each step takes during a Motr operation, therefore can furnish valuable information on what procedures serve as
If I understand it right, Motr has built-in ADDB data points to record timestamps at critical points of an operation execution, ADDB doesn't track the duration of each step directly, the duration of each step is actually calculated by analysing tool such as the one mentioned in this document.

2022-09-09 09:42 UTC, siningwuseagate commented on doc/ADDB-User-Guide.md
> +# ADDB User Guide
From the content of this document, looks like it is not a guide on how to use ADDB to instrument Motr or its applications, or a guide on how to parse and analyse ADDB records. IMO, something like "How-to analyse IO Operation using ADDB" may be a better title.

2022-09-10 02:30 UTC, faradawn commented
Dear @siningwuseagate,

I agree with your suggestions wholeheartedly. Here are the changes made accordingly:
- changed the title to "How-to analyse IO Operation using ADDB"
- refined the description to "ADDB records the activities of Motr system"

Thanks,
Faradawn

2022-09-13 08:47 UTC, siningwuseagate commented
> Dear @siningwuseagate,
> 
> I agree with your suggestions wholeheartedly. Here are the changes made accordingly:
> 
> * changed the title to "How-to analyse IO Operation using ADDB"
> * refined the description to "ADDB records the activities of Motr system"
> 
> Thanks, Faradawn

Thanks Faradawn,

The changes look good to me. We think this doc is a very good starting point for a comprehensive ADDB guide and we are looking to expand and improve this ADDB doc, to reflect this, could you please add WORK IN PROGRESS in the title?

2022-09-13 09:14 UTC, faradawn commented
Hi @siningwuseagate,

Have added "WORK IN PROGRESS" in the document title -- see if that is okay?

Thanks,
Faradawn

2022-09-14 01:29 UTC, nikitadanilov requested changes

2022-09-14 01:29 UTC, nikitadanilov commented on doc/ADDB_Record_Analyzing.md
> +- Faradawn Yang, University of Chicago, faradawn@uchicago.edu
Are you planning to extend this to a larger document? As is, this is hardly a user guide. Also, we already have doc/addb2-primer, perhaps you should use it as a base?

2022-09-14 05:56 UTC, faradawn commented
Hi @nikitadanilov,

I think we don't have more content to expand this to a larger document. Have added a "based on ADDB2-primer", is that okay?

Thanks,
Faradawn

2022-09-15 12:28 UTC, siningwuseagate approved these changes

2022-09-20 15:54 UTC, r-wambui commented
Hi @faradawn could you please update your branch, @siningwuseagate could you please merge the PR.

2022-09-21 01:44 UTC, faradawn commented
Hi @r-wambui and @siningwuseagate,

Have updated the branch! 

If there is anything I can do, please let me know!

Thanks,
Faradawn

2024-02-08 17:12 UTC, shailesh-vaidya commented
Closing as an obsolete

2024-02-08 17:12 UTC, closed without merging