provisioning: update Lustre version to 2.12.6
Seagate/cortx-motr pull request #275
Opened 2020-12-10 19:34 UTC by andriytk

2020-12-11 08:45 UTC, chumakd requested changes
minor fix needed

2020-12-11 08:45 UTC, chumakd commented on scripts/provisioning/roles/lustre-client/tasks/main.yml
>      - { version: 2.12.5, enabled: '{{ (redhat_release is version("7.8", ">=")) | ternary("yes", "no") }}' }
should be `version("7.8", "=")`

2020-12-11 10:26 UTC, andriytk commented on scripts/provisioning/roles/lustre-client/tasks/main.yml
>      - { version: 2.12.5, enabled: '{{ (redhat_release is version("7.8", ">=")) | ternary("yes", "no") }}' }
Fixed. Thanks!

2020-12-11 10:29 UTC, andriytk commented
@huanghua78, you can squash the commits here on landing. Thanks!

2020-12-11 11:31 UTC, chumakd approved these changes

2020-12-12 05:57 UTC, huanghua78 approved these changes
I've verified this patch works well on CentOS 7.9.2009

2020-12-12 06:00 UTC, merged