go/README: add a bit more info about mcp
Seagate/cortx-motr pull request #377
Opened 2021-02-01 10:12 UTC by andriytk

2021-02-01 10:14 UTC, andriytk commented
cc @chumakd

2021-02-03 03:30 UTC, huanghua78 commented on bindings/go/README.md
> +See the usame example at this discussion thread -
typo.

s/usame/usage/

2021-02-03 03:33 UTC, huanghua78 requested changes
please fix the typo.

2021-02-03 12:47 UTC, andriytk commented on bindings/go/README.md
> +See the usame example at this discussion thread -
Fixed. Thanks!

2021-02-03 12:49 UTC, andriytk commented
@huanghua78 good spot, Hua! As usual. Thanks! :)

2021-02-03 12:49 UTC, andriytk commented
Good spot, @huanghua78. Thanks!

2021-02-03 13:07 UTC, huanghua78 approved these changes
Looks fine.

2021-02-06 16:24 UTC, merged