Uploading the ISC Service User Guide
Seagate/cortx-motr pull request #420
Opened 2021-02-11 12:01 UTC by VenkyOS

2021-02-15 10:41 UTC, andriytk requested changes
A lot of code examples are given as quotations, please fix.

2021-02-16 07:47 UTC, VenkyOS commented
> A lot of code examples are given as quotations, please fix.

Can you please elaborate on what needs to be done?

2021-02-16 09:27 UTC, andriytk commented
> ... elaborate on what needs to be done?

Fix the MD-formatting, I guess?

2021-02-23 07:59 UTC, VenkyOS commented
> > ... elaborate on what needs to be done?
> 
> Fix the MD-formatting, I guess?

In .rst format, this is the way snippets are represented.

2021-02-23 08:02 UTC, huanghua78 commented on doc/ISC_Service_User_Guide.rst
> +motr_lib_init() links all the APIs. Here is an example code (please see iscservice/isc.h for more details):
Please use:
```
.. code-block:: C
```
to embed C code

2021-02-23 08:22 UTC, huanghua78 commented on doc/ISC_Service_User_Guide.rst
> +motr_lib_init() links all the APIs. Here is an example code (please see iscservice/isc.h for more details):
Please see my commits.

2021-02-23 08:22 UTC, huanghua78 approved these changes

2021-02-23 09:28 UTC, andriytk approved these changes
Looks fine now.

2021-02-25 02:51 UTC, merged