EOS-19081 : Implemented get_tick() function for insert operation
Seagate/cortx-motr pull request #559
Opened 2021-04-01 13:08 UTC by RadhaGulhane13

Signed-off-by: RadhaGulhane13 <radha.gulhane@seagate.com>

2021-04-01 13:25 UTC, RadhaGulhane13 commented
Things which are not yet implemented or needs to be discussed :
- Condition for overflow, underflow
- size of node while allocating new node if overflow : ref. line -> 717
- assign of new key value to bop->bo_rec  : ref. line -> 747-748

2021-04-02 19:23 UTC, shashank-parulekar requested changes

2021-04-02 19:23 UTC, shashank-parulekar commented on btree/btree.c
> +				struct slot slot_ = {
You cannot have the same named variable (slot_) in the same scope.

2021-04-02 19:23 UTC, shashank-parulekar commented on btree/btree.c
> +				struct slot slot_ = {
If possible use some better name maybe 'slot_for_right_node' so that code reading becomes easier.

2021-04-02 19:23 UTC, shashank-parulekar commented on btree/btree.c
> +				bop->bo_rec.r_value = l_alloc; //update bo_rec.r_value
This l_alloc needs to be another allocated node. Need to see if we saved a list of these allocated nodes at some other location.

2021-04-05 06:30 UTC, RadhaGulhane13 commented on btree/btree.c
> +			return P_CHECK;
I think ,here , we are checking if there is already lock by the operation if not we are going for lock_op_init(&bop->bo_op, &bop->bo_i->i_lop, P_CHECK); else going for P_CHECK

and wait for lock release is done by lock_op_init function when tree is lock and we want lock for that particular operation

2021-04-05 06:39 UTC, RadhaGulhane13 commented
State diagram of insertion should get changed, as we are first reaching to leaf node and then performing allocation if needed and going one level up or else to P_LOCK,
the part of state diagram :
+------+
|           |
|           v
+-----NEXTDOWN--->LOCK
   ^       |
    |       v
   +-ALLOC

should change to :

+---+
|      v
+--NEXTDOWN--> ALLOC-->LOCK
             ^     |
             +---+

2021-04-12 05:18 UTC, ydb242 commented on btree/btree.c
> +			struct slot    slot = {};
It is bad practice to keep the struct name and its variable's name the same.
Please update it.

2021-04-22 19:02 UTC, shashank-parulekar requested changes

2021-04-25 08:11 UTC, huanghua78 commented
Hello @RadhaGulhane13 , is this PR still needed?
If yes, please address the review comments.
Otherwise, please close this PR.

2021-04-26 04:40 UTC, RadhaGulhane13 commented
> Hello @RadhaGulhane13 , is this PR still needed?
> If yes, please address the review comments.
> Otherwise, please close this PR.

Yes @huanghua78 , this PR is still in progress. I have working on comments posted 23 April, also doing some other changes , Once it is done will push the code.

2021-04-26 04:41 UTC, RadhaGulhane13 commented on btree/btree.c
> +		.s_rec = bop->bo_rec;
okay

2021-04-26 04:42 UTC, RadhaGulhane13 commented on btree/btree.c
> +			struct slot *tgt;
okay

2021-04-26 04:42 UTC, RadhaGulhane13 commented on btree/btree.c
> +		    node_space(k_cookie.node)> about_to_OVERFLOW))
will do the changes

2021-05-06 11:14 UTC, closed without merging