WIP: EOS-20762: copy s3 buffer checksum to motr server
Seagate/cortx-motr pull request #734
Opened 2021-06-04 14:34 UTC by yeshpal-jain-seagate

- copy checksum values passed from s3 in attr variable to motr buffers
- send checksum fops to io service

Ex:
S3:<seg0><seg1><seg2><seg3><seg0><seg1><seg2><seg3>
iofop1:
mo_buf {
b_nob = sizeof(b_addr)
b_addr = <seg0><seg3><seg4><seg7>
}

iofop2:
mo_buf {
b_nob = sizeof(b_addr)
b_addr = <seg1><seg2><seg5><seg6>
}

Signed-off-by: Yeshpal Jain <yeshpal.jain@seagate.com>

2021-06-08 09:48 UTC, sg-shankar commented on motr/pg.h
> +	struct m0_bufvec               ti_attrbufvec;
Please add comment describing what this structure will contain

2021-06-08 10:11 UTC, sg-shankar commented on motr/io_nw_xfer.c
> +	coff    = di_cksum_offset(play, gob_offset);
I think we can move this computation inside the while loop as goff changes in while loop
coff    = di_cksum_offset(play, goff);

2021-06-08 10:18 UTC, sg-shankar commented on motr/io_nw_xfer.c
> +	ti->ti_attrbufvec.ov_vec.v_nr = nr;
Add TODO to optimize the size of buffer allocated

2021-06-08 10:20 UTC, sg-shankar requested changes
Code looks good, minor changes suggested

2021-06-12 02:31 UTC, gshipra commented on motr/io_nw_xfer.c
> +			memcpy(dst, src->ov_buf[i], len_seg - 1);
memcpy to dst will wipe off previously written data.

dst + written_till_now something like this should happen.

2021-10-21 09:04 UTC, closed without merging