EOS-22127 fdmi/fol_fdmi_src: don't post fdmi record if src dock fom is not running
Seagate/cortx-motr pull request #823
Opened 2021-07-04 20:54 UTC by max-seagate

There is a finalisation order bug that could be reproduced by adding
M0_IMPOSSIBLE() instead of return in this patch and then running

scripts/m0 run-ut -n 10000 -t m0d-ut:cs-single-service

The bug is about finalising FDMI src dock fom and then posting FDMI
record. There is no src dock fom running to consume the record at this
point, and BE tx reference is not released unless src dock fom releases
it. This leads to a situation when UT gets stuck (it will panic with
M0_IMPOSSIBLE and it just gets stuck without this patch).

The patch prints an M0_ERROR message and discards the record. It's not
the right way to handle FDMI records because they may get lost with this
approach, but it's the best short term fix.

The right fix would be to fix reqh service finalisation order in the way
that any code that may post FDMI record would be finalised before FDMI
service.

Signed-off-by: Maksym Medvied <maksym.medvied@seagate.com>

2021-07-05 02:56 UTC, huanghua78 commented
I tested this on *fdmi_int* branch, and I still got STUCK:
```
[root@cmu cortx-motr]# scripts/m0 run-ut -n 10000 -t m0d-ut:cs-single-service
----- run_ut -n 10000 -t m0d-ut:cs-single-service -----
START Iteration: 1 out of 10000
m0d-ut 
  cs-single-service                               1.72 sec  104 MiB
  [ time: 1.72 sec, mem: 104 MiB, leaked: 12 MiB ]

Time: 1.72 sec, Mem: 104 MiB, Leaked: 12 MiB, Asserts: 15
Unit tests status: SUCCESS
END   Iteration: 1 out of 10000

START Iteration: 2 out of 10000
m0d-ut 
  cs-single-service                               1.77 sec   83 MiB
  [ time: 1.77 sec, mem: 83 MiB, leaked: 0 B ]

Time: 1.78 sec, Mem: 83 MiB, Leaked: 15 EiB, Asserts: 30
Unit tests status: SUCCESS
END   Iteration: 2 out of 10000

START Iteration: 3 out of 10000
m0d-ut 
  cs-single-service                               1.46 sec   83 MiB
  [ time: 1.46 sec, mem: 83 MiB, leaked: 0 B ]

Time: 1.46 sec, Mem: 83 MiB, Leaked: 15 EiB, Asserts: 45
Unit tests status: SUCCESS
END   Iteration: 3 out of 10000

...

Time: 1.29 sec, Mem: 82 MiB, Leaked: 15 EiB, Asserts: 315
Unit tests status: SUCCESS
END   Iteration: 21 out of 10000

START Iteration: 22 out of 10000
m0d-ut 
  cs-single-service  

```

2021-07-05 04:04 UTC, huanghua78 commented
I ran this several times, and got STUCK issue similar to this (on latest fdmi_int branch with this patch):
```
[root@cmu cortx-motr]# scripts/m0 run-ut -n 10000 -t m0d-ut:cs-single-service
----- run_ut -n 10000 -t m0d-ut:cs-single-service -----
export M0_TRACE_LEVEL=fatal+
START Iteration: 1 out of 10000
m0d-ut 
  cs-single-service                               0.58 sec  103 MiB
  [ time: 0.58 sec, mem: 103 MiB, leaked: 12 MiB ]

Time: 0.58 sec, Mem: 103 MiB, Leaked: 12 MiB, Asserts: 15
Unit tests status: SUCCESS
END   Iteration: 1 out of 10000

START Iteration: 2 out of 10000
m0d-ut 
  cs-single-service                               0.39 sec   83 MiB
  [ time: 0.39 sec, mem: 83 MiB, leaked: 0 B ]

Time: 0.39 sec, Mem: 83 MiB, Leaked: 15 EiB, Asserts: 30
Unit tests status: SUCCESS
END   Iteration: 2 out of 10000

...

START Iteration: 28 out of 10000
m0d-ut 
  cs-single-service  motr[49184]:  eb60  ERROR  [fdmi/fol_fdmi_src.c:566:m0_fol_fdmi_post_record]  src dock fom is not running
motr[49184]:  eb60  ERROR  [fdmi/fol_fdmi_src.c:566:m0_fol_fdmi_post_record]  src dock fom is not running
                             1.28 sec   83 MiB
  [ time: 1.29 sec, mem: 83 MiB, leaked: 0 B ]

Time: 1.29 sec, Mem: 83 MiB, Leaked: 15 EiB, Asserts: 420
Unit tests status: SUCCESS
END   Iteration: 28 out of 10000

...

START Iteration: 31 out of 10000
m0d-ut 
  cs-single-service  
[STUCK]
```

2021-07-06 03:23 UTC, huanghua78 commented
I tried to test this patch.
This is the result.
* on main branch, without this patch. "scripts/m0 run-ut -n 2000 -t m0d-ut:cs-single-service" successfully completed.
* on fdmi_int branch, with this patch, "scripts/m0 run-ut -n 10000 -t m0d-ut:cs-single-service" STUCK at random iteration, e.g. at 20+ iteration, or at the second iteration. It is random. Please see my previous comments.

"fdmi_int branch, with this patch" means #719.  So, the #719 PR still needs more work.

2021-07-06 03:28 UTC, huanghua78 requested changes
Either this patch needs more work, or the #719 needs more work.

2021-07-06 09:37 UTC, max-seagate commented
It doesn't get stuck for me after 2000 iterations when I published this PR and 2500 iterations when I just ran it again.

Nevertheless, I see where the issue might be. Fixed. Please check now.

Running 10000 iterations on smc15-m11 in a root tmux session just to be sure.

2021-07-06 10:30 UTC, max-seagate commented
@huanghua78, @madhavemuri, @mehjoshi: please review this patch as the bug is supposed to be fixed now.

2021-07-06 19:44 UTC, shailesh-vaidya commented
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606/>Motr#606</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>2</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>57</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/606//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Bui [...]

2021-07-06 21:05 UTC, max-seagate commented
It didn't fail for me on Jenkins test node with `./configure --enable-debug`:

```START Iteration: 10000 out of 10000
m0d-ut 
  cs-single-service                               0.62 sec   83 MiB
  [ time: 0.62 sec, mem: 83 MiB, leaked: 0 B ]

Time: 0.62 sec, Mem: 83 MiB, Leaked: 15 EiB, Asserts: 150000
Unit tests status: SUCCESS
END   Iteration: 10000 out of 10000

utime 9957.326443 stime 1931.116774 maxrss 1895664 nvcsw 21163577 nivcsw 595902
minflt 15204905 majflt 4 inblock 852888 oublock 54820608
rchar 129481932 wchar 2889457 syscr 311281 syscw 70090```

2021-07-07 08:15 UTC, max-seagate commented
```
START Iteration: 30000 out of 30000
m0d-ut 
  cs-single-service                               1.45 sec   83 MiB
  [ time: 1.45 sec, mem: 83 MiB, leaked: 0 B ]

Time: 1.45 sec, Mem: 83 MiB, Leaked: 15 EiB, Asserts: 450000
Unit tests status: SUCCESS
END   Iteration: 30000 out of 30000

utime 12771.263541 stime 6771.604776 maxrss 6553944 nvcsw 70580923 nivcsw 1681148
minflt 455477700 majflt 4 inblock 2623208 oublock 144086080
rchar 383572930 wchar 8594979 syscr 931301 syscw 210095
read_bytes 1343082496 write_bytes 73772150784 cancelled_write_bytes 0
```
Jenkins test node, 30k iterations.

2021-07-07 13:11 UTC, huanghua78 commented
Please note, I was reporting failure of this test, on fdmi_int branch, with this patch!!

It is not on main branch with this patch.

2021-07-07 16:10 UTC, max-seagate commented
@huanghua78: do you think this failure is introduced in one of the patches from `fdmi_int` branch? Do you have stack backtrace, core dump, proper `m0reportbug` archives from the failure?

In the meantime I'm going to run 30k iterations on the Jenkins test node I'm using currently for testing.

2021-07-07 20:09 UTC, max-seagate commented
@huanghua78: I've got another failure in `fdmi_int` branch:
```
START Iteration: 11427 out of 30000
m0d-ut 
  cs-single-service  motr[274734]:  5b10  FATAL  [lib/assert.c:50:m0_panic]  panic: (ast->sa_next != ((void *)0)) at m0_sm_asts_run() (sm/sm.c:164)  [git: d594e4a] /var/motr/m0ut/m0trace.274734
Motr panic: (ast->sa_next != ((void *)0)) at m0_sm_asts_run() sm/sm.c:164 (errno: 0) (last failed: none) [git: d594e4a] pid: 274734  /var/motr/m0ut/m0trace.274734
/w/motr/motr/.libs/libmotr.so.2(m0_arch_backtrace+0x20)[0x7fe53ca4e030]
/w/motr/motr/.libs/libmotr.so.2(m0_arch_panic+0xe6)[0x7fe53ca4e1e6]
/w/motr/motr/.libs/libmotr.so.2(+0x371004)[0x7fe53ca3d004]
/w/motr/motr/.libs/libmotr.so.2(m0_sm_asts_run+0x16d)[0x7fe53cad81cd]
/w/motr/motr/.libs/libmotr.so.2(+0x345f67)[0x7fe53ca11f67]
/w/motr/motr/.libs/libmotr.so.2(m0_thread_trampoline+0x5e)[0x7fe53ca4410e]
/w/motr/motr/.libs/libmotr.so.2(+0x382e9d)[0x7fe53ca4ee9d]
/lib64/libpthread.so.0(+0x7e65)[0x7fe53c1b5e65]
/lib64/libc.so.6(clone+0x6d)[0x7fe53b05688d]
/w/motr/utils/m0run: line 416: 274734 Aborted                 (core dumped) $(srcdir_path_of $binary) "$@"

real    156m42.259s
user    79m41.712s
sys     31m11.296s
[root@smc15-m11 motr]# git log -1
commit d594e4aaa47ccd6d293b840f62875ab46d6d16d8
Author: Maksym Medvied <maksym.medvied@seagate.com>
Date:   Thu May 20 21:41:59 2021 +0300

    EOS-20819 fop/fom_generic: post FDMI record when BE tx becomes LOGGED
```
```
(gdb) bt
#0  0x00007fe53af8e337 in raise () from /lib64/libc.so.6
#1  0x00007fe53af8fa28 in abort () from /lib64/libc.so.6
#2  0x00007fe53ca4e1f5 in m0_arch_panic (c=c@entry=0x7fe53cf6d0e0 <__pctx.7206>, ap=ap@entry=0x7fe51f7d5b88) at lib/user_space/uassert.c:131
#3  0x00007fe53ca3d004 in m0_panic (ctx=ctx@entry=0x7fe53cf6d0e0 <__pctx.7206>) at lib/assert.c:52
#4  0x00007fe53cad81cd in m0_sm_asts_run (grp=grp@entry=0x108b4c0) at sm/sm.c:164
#5  0x00007fe53ca11f67 in loc_handler_thread (th=0x108f530) at fop/fom.c:925
#6  0x00007fe53ca4410e in m0_thread_trampoline (arg=arg@entry=0x108f538) at lib/thread.c:117
#7  0x00007fe53ca4ee9d in uthread_trampoline (arg=0x108f538) at lib/user_space/uthread.c:98
#8  0x00007fe53c1b5e65 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fe53b05688d in clone () from /lib64/libc.so.6
(gdb) frame 4
#4  0x00007fe53cad81cd in m0_sm_asts_run (grp=grp@entry=0x108b4c0) at sm/sm.c:164
164                     M0_ASSERT(ast->sa_next != NULL);
(gdb) p ast
$1 = (struct m0_sm_ast *) 0x7fe53d0264c0 <fdmi_global_src_dock+1728>```
```
Thread 100 (Thread 0x7fe5489b3840 (LWP 274734)):
#0  0x00007fe53c1bbafb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
#1  0x00007fe53c1bbb8f in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007fe53c1bbc2b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x00007fe53ca4d494 in m0_semaphore_down (semaphore=semaphore@entry=0x7fe53d026640 <fdmi_global_src_dock+2112>) at lib/user_space/semaphore.c:62
#4  0x00007fe53ca0affc in m0_fdmi__src_dock_fom_stop (src_dock=0x7fe53d025e00 <fdmi_global_src_dock>) at fdmi/source_dock_fom.c:280
#5  0x00007fe53caae49e in m0_reqh_service_prepare_to_stop (service=service@entry=0x33c93500) at reqh/reqh_service.c:399
#6  0x00007fe53caacd53 in m0_reqh_services_prepare_to_stop (reqh=reqh@entry=0x7fffb4939e68, level=level@entry=10) at reqh/reqh.c:632
#7  0x00007fe53caacddd in m0_reqh_shutdown (reqh=reqh@entry=0x7fffb4939e68) at reqh/reqh.c:644
#8  0x00007fe53caace21 in m0_reqh_shutdown_wait (reqh=reqh@entry=0x7fffb4939e68) at reqh/reqh.c:649
#9  0x00007fe53e0a4b54 in cs_reqh_shutdown (rctx=0x7fffb4934ec8) at /w/motr/motr/setup.c:1694
#10 cs_level_leave (module=<optimized out>) at /w/motr/motr/setup.c:2847
#11 0x00007fe53ca8d9b6 in m0_module_fini (module=module@entry=0x7fffb4942458, level=level@entry=-1) at module/module.c:154
#12 0x00007fe53e0a828d in m0_cs_fini (cctx=cctx@entry=0x7fffb4934bb8) at /w/motr/motr/setup.c:2986
#13 0x00007fe53cad2b39 in m0_rpc_server_stop (sctx=sctx@entry=0x7fffb4934b90) at rpc/rpclib.c:89
#14 0x00007fe53e0a8b18 in cs_ut_test_helper_success (cctx=cctx@entry=0x7fffb4943600, cctx_nr=cctx_nr@entry=1, cs_argv=cs_argv@entry=0x7fe53e568fa0 <cs_ut_service_one_cmd>, cs_argc=cs_argc@entry=19) at motr/ut/cs_ut_main.c:315
#15 0x00007fe53e0a8cfb in test_cs_ut_service_one () at motr/ut/cs_ut_main.c:354
#16 0x00007fe53e1531a3 in run_test (max_name_len=43, test=0x64ea08 <m0d_ut+4488>) at ut/ut.c:390
#17 run_suite (max_name_len=43, suite=0x64d880 <m0d_ut>) at ut/ut.c:459
#18 tests_run_all (m=0x7fe548799ae0 <ut.12949>) at ut/ut.c:513
#19 m0_ut_run () at ut/ut.c:539
#20 0x00000000004045f6 in main (argc=5, argv=0x7fffb4947be8) at ut/m0ut.c:521
```
It doesn't seem that the patch introduces this bug. What do you think? `tmux` for `root` on `smc15-m11` has the relevant place and the core dump open right now (in case if you want to look).

And, btw, 11427 iterations of the UT were required to reproduce it this time.

2021-07-08 04:40 UTC, huanghua78 commented
> @huanghua78: do you think this failure is introduced in one of the patches from `fdmi_int` branch? Do you have stack backtrace, core dump, proper `m0reportbug` archives from the failure?
> 
> In the meantime I'm going to run 30k iterations on the Jenkins test node I'm using currently for testing.

As I commented, the initial patch did not fix the issue in fdmi_int branch.
So, you had an update in 067a702, and after that the issue is gone.

2021-07-15 03:49 UTC, huanghua78 approved these changes
I have verified this patch works.

2021-07-15 04:03 UTC, huanghua78 commented
I am asking @yumanets to review this patch.

2021-07-20 16:52 UTC, yumanets approved these changes
Looks good.

2021-07-21 03:43 UTC, huanghua78 commented
This PR is targeted for 'fdmi_int' branch in #719.
It has been included in #719.

As this PR is reviewed and approved, I am closing this PR.

2021-07-21 03:43 UTC, closed without merging