EOS-22555: Callback invokation on transaction commit.
Seagate/cortx-motr pull request #896
Opened 2021-07-29 07:51 UTC by NikhilBirgade

- Also includes UT for tx callback feature.

Signed-off-by: Nikhil Kumar Birgade <nikhil.birgade@seagate.com>

2021-07-29 12:33 UTC, RadhaGulhane13 approved these changes

2021-08-02 09:18 UTC, ydb242 approved these changes

2021-08-02 17:24 UTC, shashank-parulekar requested changes

2021-08-03 04:53 UTC, NikhilBirgade commented on be/tx.c
> +	if (state == M0_BTS_DONE && tx->t_prepared.tc_cb_nr != 0)
Okay.

2021-08-03 10:56 UTC, shashank-parulekar approved these changes

2021-08-03 11:46 UTC, merged