lib: add m0_bitmap_ffs()
Seagate/cortx-motr pull request #948
Opened 2021-08-12 13:52 UTC by andriytk

Add "find fist bit set" function to m0_bitmap.

2021-08-12 14:22 UTC, nikitadanilov requested changes

2021-08-12 14:22 UTC, nikitadanilov commented on lib/bitmap.h
> +   Find first non-zero (a.k.a. set, true) bit from a bitmap.
"Finds the".

2021-08-12 14:22 UTC, nikitadanilov commented on lib/bitmap.c
> +	return (size_t)-1;
Why the cast is needed?

2021-08-12 14:47 UTC, andriytk commented on lib/bitmap.c
> +	return (size_t)-1;
Fixed.

2021-08-12 14:48 UTC, andriytk commented on lib/bitmap.h
> +   Find first non-zero (a.k.a. set, true) bit from a bitmap.
Fixed.

2021-08-12 14:51 UTC, huanghua78 commented on lib/bitmap.c
> +		idx = __builtin_ffsll(map->b_words[i]);
Is this GCC built-in function?
If we want to port to other platform, e.g. ARM, is it still available?

2021-08-12 15:25 UTC, huanghua78 approved these changes

2021-08-13 09:11 UTC, max-seagate approved these changes
[* suggestion *]

s/

> lib: add m0_bitmap_ffs()

/

lib/bitmap: add m0_bitmap_ffs()

/

In this case a bit of time is saved when someone goes through the commit history in `git log` or `git log --oneline`.

2021-08-13 10:52 UTC, ivan-alekhin approved these changes

2021-08-13 12:03 UTC, mehjoshi approved these changes

2021-08-16 13:31 UTC, nikitadanilov approved these changes

2021-08-16 16:02 UTC, merged